config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'categories#index'

  resources :categories, only: [:show] do
    get ':id', to: 'categories#show_articles', as: :articles
  end

  resources :articles, only: [:new, :create] do
    collection do
      get 'get_category_parents', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category, optional: true
  has_many :pages, dependent: :destroy

  enum format:{ multiple: 0, only_one: 1 }
  # multiple = 複数選択問題, only_one = 択一問題

  scope :new_order, -> { order(created_at: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :nullify
  has_ancestry

  validates :name, presence: true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :page
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :article
  has_many :options, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  validates :nickname, presence: true, uniqueness: true, length: { in: 2..14 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { in: 8..100 }, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,100}+\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birth_on, :profile, :image])	
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_root_categories, only: [:new, :create]

  def new
    @article = FormArticle.new
  end

  def create
    @article = FormArticle.new(article_params)
    if @article.save
      redirect_to root_path, notice: "問題を作成しました"
    else
      flash.now[:alert] = "問題の作成に失敗しました"
      render :new
    end
  end

  def set_root_categories
    @root_categories = Category.roots
  end

  # 以下json formatのアクション
  def get_category_parents
    # 選択されたルートカテゴリに紐付く親カテゴリの配列を取得
    @category_parents = Category.find_by(id: "#{params[:root_id]}",ancestry: nil).children
  end

  def get_category_children
    # 選択された親カテゴリに紐付く子カテゴリの配列を取得
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  private
  def article_params
    params.require(:form_article).permit(:article_category,
                                    :article_title,
                                    :article_price,
                                    :article_time_limit,
                                    :article_public,
                                    :page_text,
                                    :option_correct,
                                    :option_wrong
                                    ).merge(created_user_id: current_user.id,
                                            article_format: 0)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_root_categories, only: [:index, :show, :show_articles]

  def index
    @new_articles = Article.new_order.limit(10)
  end

  def show
    @current_category = Category.find(params[:id])
    @current_category_children = @current_category.children
    @preview_children_categories = @current_category_children.first.children
  end

  def show_articles
    @current_root_category = Category.find(params[:category_id])
    @current_root_category_children = @current_root_category.children
    @current_parent_category = Category.find(params[:id])
    @current_parent_category_children = @current_parent_category.children
  end

  def set_root_categories
    @root_categories = Category.roots
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/new.html.haml
.new-article
  %header
    = link_to root_path do
      = image_tag "/assets/png/eLS_logo.png", alt: "title_logo"
  = form_with url: "#" do |f|
    .question_format
      %label.question_format__label 出題形式
      = f.select :article_format, Article.formats_i18n.invert, {}, class: "question_format__select"
  = simple_form_for @article, url: { controller: 'articles', action: 'create' }, local: true do |f|
    = render 'layouts/error_messages', model: f.object
    .article1
      .article1__categories
        %p.article1__categories__category-name カテゴリー
        = f.collection_select :article_category, @root_categories, :id, :name, { prompt: "選択してください" }, id: "articleCategory", class: "article1__categories__category-select"
      #categoriesAppend.article1__categories
      .article1__title
        %label.article1__title__name タイトル
        = f.input_field :article_title, label: false, error: false, placeholder: "タイトルを入力してください", class: "article1__title__input"
    #pages.pages
      .pages__page
        .pages__page__container
          %label.pages__page__container__name 問題文
          .pages__page__container__text
            = f.text_area :page_text, class: "pages__page__container__text__area", placeholder: "問題文を入力してください。", required: true
        #correct.pages__page__container
          %label.pages__page__container__name-block 正答
          .pages__page__container__add-form
            = icon('fas', 'plus')
          .pages__page__container__answer
            = f.input_field :option_correct, label: false, placeholder: "正解の選択肢を入力してください", class: "form"
        #wrong.pages__page__container
          %label.pages__page__container__name-block 誤答
          .pages__page__container__add-form
            = icon('fas', 'plus')
          .pages__page__container__answer
            = f.input_field :option_wrong, label: false, placeholder: "不正解の選択肢を入力してください", class: "form"
    .article2
      .article2__container
        %label.article2__container__name 料金（未入力の場合は無料）
        .article2__container__input
          = f.input_field :article_price, label: false, class: "form", placeholder: "100〜999,000"
          円
      .article2__container
        %label.article2__container__name 制限時間（未入力の場合は無制限）
        .article2__container__input
          = f.input_field :article_time_limit, class: "form", placeholder: "0〜120"
          分
      .article2__container
        %label.article2__container__name 公開する
        .article2__container__select
          = f.input :article_public, as: :boolean, label: false, input_html: { class: "public" }
      .article2__submit
        = f.button :submit, value: "問題作成", class: "article2__submit__btn"

app/views/categories/_articles.html.haml
.article
  = link_to "#" do
    = article.title

app/views/categories/_side_bar.html.haml
%nav#categories-side
  .title カテゴリー
  %ul
    - root_categories.each do |category|
      %li
        = link_to category_path(category.id) do
          = category.name

app/views/categories/index.html.haml
#container
  = render 'shared/header'
  #main
    = render 'side_bar', root_categories: @root_categories
    .contents
      .title 新着の問題
      .new_articles
        - @new_articles.each do |article|
          .new_articles__article
            -# 問題購入機能実装後にパス変更
            = link_to "#", class: "new_articles__article__title" do
              = article.title
            .new_articles__article__category
              = "#{article.category.root.name} / #{article.category.parent.name} / #{article.category.name}"
            .new_articles__article__created_at
              = "#{time_ago_in_words(article.created_at)}前"

app/views/categories/show.html.haml
#container
  = render 'shared/header'
  #main
    = render 'side_bar', root_categories: @root_categories
    .category-contents
      .root-name
        = @current_category.name
      .parents
        - @current_category_children.each do |parent_category|
          .parents__parent-name
            = link_to "#{params[:id]}/#{parent_category.id}" do
              = parent_category.name
      .selected-parent
        = "#{@current_category_children.first.name} の問題"
      - @preview_children_categories.each do |child_category|
        .category-articles
          .child-name
            = icon('fas', 'plus-square')
            = child_category.name
          .articles
            = render partial: "articles", collection: child_category.articles, as: :article

app/views/categories/show_articles.html.haml
#container
  = render 'shared/header'
  #main
    = render 'side_bar', root_categories: @root_categories
    .category-contents
      .root-name
        = @current_root_category.name
      .parents
        - @current_root_category_children.each do |parent_category|
          .parents__parent-name
            = link_to "#{parent_category.id}" do
              = parent_category.name
      .selected-parent
        = "#{@current_parent_category.name} の問題"
      - @current_parent_category_children.each do |child_category|
        .category-articles
          .child-name
            = icon('fas', 'plus-square')
            = child_category.name
          .articles
            = render partial: "articles", collection: child_category.articles, as: :article

app/views/layouts/_error_messages.html.haml
- if model.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",
        count: model.errors.count,
        model: model.class.model_name.human.downcase)
    %ul
      - model.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ELearningSystem
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/shared/_header.html.haml
%header#header.top
  .inner
    .inner__left
      - if user_signed_in?
        .user-photo
          = link_to '#' do 
            = image_tag "/assets/png/profile.png", alt: "プロフィール写真"
      .logo
        = link_to root_path do
          = image_tag "/assets/png/eLS_logo.png", alt: "title_logo"
    .search
      = form_with(url: '#' , method: :get, local: :true) do |f|
        = f.text_field :search_word, class: 'search__window', placeholder: 'キーワード検索'
        = f.button type: 'submit', class: 'search__btn' do
          = icon('fas', 'search')
    - if user_signed_in?
      .tmp-signout
        = link_to "サインアウト", destroy_user_session_path, method: :delete
    - else
      .tmp-signup
        = link_to "ユーザー登録", new_user_registration_path
      .tmp-signin
        = link_to "ログイン", new_user_session_path

    = link_to new_article_path do
      .create-new
        = icon('fas', 'edit', class: 'create-new__icon')
        新規作成

app/views/shared/_user_side_bar.html.haml
- if user_signed_in?
  %nav#login-side
    %ul
      %li.name
        = current_user.nickname
      %li.followed
        = link_to "フォローユーザー", '#' 
      %li.menu__purchased
        = link_to "購入した問題", '#'
      %li.menu__group
        = link_to "マイグループ", '#'
      %li.menu__created
        = link_to "作成した問題", '#'
      %li.menu__sales
        = link_to "売上", '#'

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_form.html.haml
#container
  %header#header.user
    .logo
      = link_to root_path do
        = image_tag "/assets/png/eLS_logo.png", alt: "title_logo"
    - if "#{controller_name}" == "registrations"
      = link_to new_user_session_path, class: "link" do
        .link__btn
          = icon('fas', 'share-square')
          既にアカウントをお持ちの方はこちら
    - elsif "#{controller_name}" == "sessions"
      = link_to new_user_registration_path, class: "link" do
        .link__btn
          = icon('fas', 'share-square')
          アカウントをお持ちではない方はこちら
  #inner
    .main
      - if "#{controller_name}" == "registrations"
        = form_with(model: @user, url: user_registration_path, class: 'form', local: true) do |f|
          %h1.title 無料登録
          .form__color
            .form__color__area
              .form__color__area__name ユーザー名:
              .form__color__area__attention ２文字以上１４文字以内
              .form__color__area__input
                = f.label :nickname, class: "form__color__area__input__icon" do
                  %p
                    = icon('fas', 'signature')
                = f.text_field :nickname, id: "user_nickname", class: "form__color__area__input__field", minlength:2, maxlength: 14, required: true
            .form__color__area
              .form__color__area__name メールアドレス:
              .form__color__area__attention
              .form__color__area__input
                = f.label :email, class: "form__color__area__input__icon" do
                  %p
                    = icon('far', 'envelope')
                = f.email_field :email, id: "user_email", class: "form__color__area__input__field", required: true
            .form__color__area
              .form__color__area__name パスワード:
              .form__color__area__attention 半角英字と半角数字各1文字以上含む8文字以上
              .form__color__area__input
                = f.label :password, class: "form__color__area__input__icon" do
                  %p
                    = icon('fas', 'lock')
                = f.password_field :password, id: "user_password", class: "form__color__area__input__field", pattern: "^(?=.*?[a-zA-Z])(?=.*?\\d)[a-zA-Z\\d]{8,100}$", required: true
            .submit
              = f.submit "新規登録", class: 'submit__btn'
      - elsif "#{controller_name}" == "sessions"
        = form_with(scope: :user, url: session_path(resource_name), local: true, class: 'form') do |f|
          %h1.title ログイン
          .form__color
            .form__color__area
              .form__color__area__name メールアドレス:
              .form__color__area__input
                = f.label :email, class: "form__color__area__input__icon" do
                  %p
                    = icon('far', 'envelope')
                = f.email_field :email, id: "user_email", class: "form__color__area__input__field", required: true
            .form__color__area
              .form__color__area__name パスワード:
              .form__color__area__input
                = f.label :password, class: "form__color__area__input__icon" do
                  %p
                    = icon('fas', 'lock')
                = f.password_field :password, id: "user_password", class: "form__color__area__input__field", pattern: "^(?=.*?[a-zA-Z])(?=.*?\\d)[a-zA-Z\\d]{8,100}$", required: true
            .submit
              = f.submit "ログイン", class: 'submit__btn'
      .description
        %p
          興味と知識を共有できるWebサービス
          %br
          e-learning_system
          %br
          さあ、リテラシーをシェアしよう！

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/